import { Bell, CheckCircle2, Lock, UserRound } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export default function SettingsPage() {
  return <div className="mx-auto flex max-w-4xl flex-col gap-8"><div><p className="text-sm font-medium uppercase tracking-[.18em] text-primary">Workspace settings</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Make FolioLabs yours.</h1><p className="mt-2 text-muted-foreground">Manage your identity, privacy, and notification preferences.</p></div><Card><CardHeader><div className="flex items-center gap-3"><UserRound className="size-5 text-primary" /><div><CardTitle>Profile</CardTitle><CardDescription>How your identity appears across your workspace.</CardDescription></div></div></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="name">Display name</Label><Input id="name" defaultValue="Alex Morgan" /></div><div className="grid gap-2"><Label htmlFor="institution">Institution</Label><Input id="institution" defaultValue="MIT" /></div><div className="grid gap-2 sm:col-span-2"><Label htmlFor="bio">Short bio</Label><Input id="bio" defaultValue="Computational mathematics and network analysis." /></div><Button className="w-fit">Save profile</Button></CardContent></Card><Card><CardHeader><div className="flex items-center gap-3"><Bell className="size-5 text-primary" /><div><CardTitle>Notifications</CardTitle><CardDescription>Stay in the loop without losing focus.</CardDescription></div></div></CardHeader><CardContent className="flex flex-col gap-4">{["New opportunity matches", "Faculty verification updates", "Weekly portfolio signal"].map((item) => <div key={item} className="flex items-center justify-between rounded-xl border border-border p-4"><div className="flex items-center gap-3"><CheckCircle2 className="size-4 text-primary" /><span className="text-sm">{item}</span></div><span className="text-xs text-primary">Enabled</span></div>)}</CardContent></Card><Card><CardHeader><div className="flex items-center gap-3"><Lock className="size-5 text-primary" /><div><CardTitle>Privacy</CardTitle><CardDescription>Control how your verified work is shared.</CardDescription></div></div></CardHeader><CardContent><div className="flex flex-col gap-4"><div className="flex items-center justify-between rounded-xl border border-border p-4"><div><p className="text-sm font-medium">Portfolio visibility</p><p className="mt-1 text-xs text-muted-foreground">Your verified portfolio can be shared by link.</p></div><span className="rounded-full bg-primary/12 px-3 py-1 text-xs font-medium text-primary">Public link</span></div><Button variant="outline" className="w-fit">Manage sharing</Button></div></CardContent></Card></div>
}
