import Link from "next/link"
import { ArrowRight, BellRing, Clock3, Sparkles } from "lucide-react"
import { Logo } from "@/components/logo"
import { Button, buttonVariants } from "@/components/ui/button"
import { cn } from "@/lib/utils"

export default function ComingSoonPage() {
	return <main className="relative flex min-h-svh items-center justify-center overflow-hidden bg-background px-5 py-12"><div className="pointer-events-none absolute inset-0 opacity-50 [background-image:linear-gradient(to_right,rgba(255,255,255,.04)_1px,transparent_1px),linear-gradient(to_bottom,rgba(255,255,255,.04)_1px,transparent_1px)] [background-size:52px_52px]" /><div className="pointer-events-none absolute left-1/2 top-0 size-[520px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary/10 blur-3xl" /><div className="relative z-10 flex w-full max-w-2xl flex-col items-center text-center"><Logo /><div className="mt-16 flex size-16 items-center justify-center rounded-2xl border border-primary/25 bg-primary/10 text-primary"><Clock3 className="size-7" /></div><p className="mt-7 inline-flex items-center gap-2 text-xs font-medium uppercase tracking-[.18em] text-primary"><Sparkles className="size-3.5" /> A thoughtful workspace is taking shape</p><h1 className="mt-4 text-balance text-4xl font-semibold tracking-tight sm:text-6xl">FolioLabs is coming soon.</h1><p className="mt-5 max-w-xl text-pretty text-base leading-7 text-muted-foreground">We are building a calmer way to turn projects, evidence, and reflection into work you can stand behind.</p><div className="mt-9 flex w-full max-w-md flex-col gap-3 sm:flex-row"><Link className={cn(buttonVariants(), "flex-1")} href="/signup"><BellRing data-icon="inline-start" /> Sign up for updates</Link><Link className={cn(buttonVariants({ variant: "outline" }), "flex-1")} href="/welcome">Explore FolioLabs <ArrowRight data-icon="inline-end" /></Link></div><p className="mt-5 text-xs text-muted-foreground">Already invited? <Link href="/" className="font-medium text-primary hover:underline">Sign in</Link></p></div></main>
}
