"use client"

import { useState } from "react"
import { CheckCircle2, ClipboardCheck } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

const questions = [{ q: "What happens when a vector is aligned with an eigenvector?", options: ["It changes direction randomly", "It stays on the same line and scales", "It becomes zero"] }, { q: "Which observation best supports a claim about invariant direction?", options: ["A single screenshot", "Repeated transformations with consistent direction", "A longer conclusion"] }]
export default function AssessmentPage() { const [answers, setAnswers] = useState<number[]>([]); const [submitted, setSubmitted] = useState(false); const score = answers.filter((answer, i) => answer === [1, 1][i]).length; return <main className="mx-auto flex w-full max-w-4xl flex-col gap-6 p-6"><div><p className="text-sm font-medium text-primary">Learn & Build / Assessment</p><h1 className="mt-2 text-3xl font-semibold">Practical understanding check</h1><p className="mt-2 text-muted-foreground">Explain what your experiments demonstrate before you submit.</p></div>{submitted ? <Card><CardContent className="flex flex-col items-center gap-4 py-12 text-center"><CheckCircle2 className="size-12 text-primary" /><p className="text-4xl font-semibold">{Math.round(score / questions.length * 100)}%</p><p className="text-muted-foreground">Attempt recorded as learning evidence.</p><Button onClick={() => { setAnswers([]); setSubmitted(false) }}>Try again</Button></CardContent></Card> : <div className="flex flex-col gap-4">{questions.map((question, index) => <Card key={question.q}><CardHeader><CardTitle className="text-base">{index + 1}. {question.q}</CardTitle></CardHeader><CardContent className="flex flex-col gap-2">{question.options.map((option, optionIndex) => <button key={option} onClick={() => setAnswers((current) => { const next = [...current]; next[index] = optionIndex; return next })} className={`rounded-lg border px-4 py-3 text-left text-sm transition-colors ${answers[index] === optionIndex ? "border-primary bg-primary/10" : "border-border hover:bg-muted/40"}`}>{option}</button>)}</CardContent></Card>)}<Button className="self-start" disabled={answers.length !== questions.length} onClick={() => setSubmitted(true)}>Submit assessment</Button></div>}</main> }
