import type {
  User,
  Project,
  Evidence,
  LabExperiment,
  FacultyReview,
  TimelineEvent,
  Stats,
} from './types'

export const demoUser: User = {
  id: 'user-1',
  name: 'Alex Morgan',
  email: 'alex.morgan@university.edu',
  role: 'student',
  bio: 'Studying computational mathematics and linear algebra applications in network analysis.',
  institution: 'MIT',
  authenticityScore: 94,
}

export const demoProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Eigenvector Centrality in Social Networks',
    description: 'Analyzing network structure through eigenvalue decomposition',
    category: 'research',
    startDate: '2025-09-01',
    status: 'active',
    owner: 'user-1',
    collaborators: ['user-2', 'user-3'],
    progress: 75,
    tags: ['linear-algebra', 'networks', 'computation'],
  },
  {
    id: 'proj-2',
    name: 'Community Detection Algorithm',
    description: 'Implementing spectral clustering for graph partitioning',
    category: 'research',
    startDate: '2025-08-15',
    endDate: '2025-11-30',
    status: 'active',
    owner: 'user-1',
    collaborators: ['user-4'],
    progress: 55,
    tags: ['algorithms', 'graph-theory', 'python'],
  },
  {
    id: 'proj-3',
    name: 'Signal Processing Optimization',
    description: 'Optimizing signal reconstruction using sparse matrices',
    category: 'research',
    startDate: '2025-07-01',
    endDate: '2025-10-15',
    status: 'completed',
    owner: 'user-1',
    collaborators: [],
    progress: 100,
    tags: ['optimization', 'signal-processing'],
  },
]

export const demoEvidence: Evidence[] = [
  {
    id: 'ev-1',
    projectId: 'proj-1',
    type: 'milestone',
    title: 'Initial Literature Review Complete',
    description: 'Reviewed 25 foundational papers on network analysis',
    content: 'Completed comprehensive review of spectral graph theory fundamentals...',
    attachments: [],
    createdAt: '2025-09-05',
    createdBy: 'user-1',
    verified: true,
    verifiedBy: 'user-5',
  },
  {
    id: 'ev-2',
    projectId: 'proj-1',
    type: 'artifact',
    title: 'Eigenvector Computation Implementation',
    description: 'Python implementation of QR algorithm for eigenvalue decomposition',
    content: 'Successfully implemented QR-based eigenvalue solver achieving 10^-10 precision...',
    attachments: ['github.com/alexmorgan/eigen-solver'],
    createdAt: '2025-09-15',
    createdBy: 'user-1',
    verified: true,
    verifiedBy: 'user-5',
  },
  {
    id: 'ev-3',
    projectId: 'proj-1',
    type: 'reflection',
    title: 'Mid-Project Reflection',
    description: 'Lessons learned from implementing spectral methods',
    content:
      'The eigenvalue computation was more nuanced than anticipated. Numerical stability proved critical...',
    attachments: [],
    createdAt: '2025-09-20',
    createdBy: 'user-1',
    verified: false,
  },
  {
    id: 'ev-4',
    projectId: 'proj-2',
    type: 'peer-feedback',
    title: 'Peer Code Review',
    description: 'Colleague review of clustering implementation',
    content: 'Clear algorithm structure, good handling of edge cases...',
    attachments: [],
    createdAt: '2025-09-18',
    createdBy: 'user-4',
    verified: true,
    verifiedBy: 'user-5',
  },
]

export const demoLabExperiments: LabExperiment[] = [
  {
    id: 'lab-1',
    projectId: 'proj-1',
    title: 'Network Centrality Analysis - Iteration 1',
    hypothesis: 'Eigenvector centrality accurately identifies influential nodes',
    methodology: 'Applied eigendecomposition to 1000-node synthetic network',
    results: 'Top 10 central nodes identified with 94% precision vs PageRank',
    reasoning: 'Eigenvalues accurately capture node influence via recursive relationships',
    timestamp: '2025-09-12',
    status: 'analyzed',
    matrixData: {
      rows: 5,
      cols: 5,
      values: [
        [2.5, 0.8, 0.3, 0.1, 0.2],
        [0.8, 1.8, 0.5, 0.2, 0.1],
        [0.3, 0.5, 1.2, 0.4, 0.6],
        [0.1, 0.2, 0.4, 0.9, 0.3],
        [0.2, 0.1, 0.6, 0.3, 1.1],
      ],
      eigenvalues: [4.2, 2.1, 1.3, 0.8, 0.4],
      eigenvectors: [
        [0.58, 0.42, 0.31, 0.15, 0.18],
        [0.43, 0.51, 0.28, 0.22, 0.12],
        [0.32, 0.35, 0.62, 0.31, 0.38],
        [0.18, 0.25, 0.35, 0.72, 0.25],
        [0.22, 0.18, 0.48, 0.25, 0.82],
      ],
    },
  },
]

export const demoReviews: FacultyReview[] = [
  {
    id: 'rev-1',
    projectId: 'proj-1',
    reviewer: {
      id: 'user-5',
      name: 'Dr. Sarah Chen',
      email: 's.chen@university.edu',
      role: 'faculty',
      avatar: '',
      institution: 'MIT',
    },
    rating: 5,
    feedback:
      'Exceptional work on eigenvalue decomposition. Clear methodology and strong theoretical foundation.',
    verificationStatus: 'verified',
    timestamp: '2025-09-21',
  },
  {
    id: 'rev-2',
    projectId: 'proj-3',
    reviewer: {
      id: 'user-6',
      name: 'Prof. James Williams',
      email: 'j.williams@university.edu',
      role: 'faculty',
      avatar: '',
      institution: 'MIT',
    },
    rating: 5,
    feedback:
      'Outstanding optimization work. Innovative approach to sparse matrix reconstruction.',
    verificationStatus: 'verified',
    timestamp: '2025-10-15',
  },
]

export const demoTimeline: TimelineEvent[] = [
  {
    id: 'tl-1',
    projectId: 'proj-1',
    type: 'milestone',
    title: 'Project Started',
    description: 'Eigenvector Centrality research initiated',
    date: '2025-09-01',
    icon: 'check',
    verified: true,
  },
  {
    id: 'tl-2',
    projectId: 'proj-1',
    type: 'evidence',
    title: 'Literature Review Submitted',
    description: 'Core research paper analysis documented',
    date: '2025-09-05',
    icon: 'doc',
    verified: true,
  },
  {
    id: 'tl-3',
    projectId: 'proj-1',
    type: 'evidence',
    title: 'Implementation Complete',
    description: 'Eigenvalue solver deployed and tested',
    date: '2025-09-15',
    icon: 'star',
    verified: true,
  },
  {
    id: 'tl-4',
    projectId: 'proj-1',
    type: 'review',
    title: 'Faculty Verification',
    description: 'Work reviewed and verified by Dr. Chen',
    date: '2025-09-21',
    icon: 'shield',
    verified: true,
  },
]

export const demoStats: Stats = {
  activeProjects: 2,
  completedProjects: 3,
  authenticityScore: 94,
  defensesScheduled: 1,
  evidenceCount: 8,
  portfolioItems: 5,
  collaborators: 4,
}

export const facultyProfiles = [
  {
    id: 'user-5',
    name: 'Dr. Sarah Chen',
    title: 'Professor of Applied Mathematics',
    specialty: 'Linear Algebra & Networks',
    verified: true,
    projectsReviewed: 12,
    avatar: '',
  },
  {
    id: 'user-6',
    name: 'Prof. James Williams',
    title: 'Senior Research Scientist',
    specialty: 'Signal Processing & Optimization',
    verified: true,
    projectsReviewed: 18,
    avatar: '',
  },
]
