'use client'

import { useState } from 'react'
import { Check, FlaskConical, Play, RotateCcw, Volume2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { demoLabExperiments } from '@/lib/demo-data'

export default function LabPage() {
  const [values, setValues] = useState(demoLabExperiments[0].matrixData?.values ?? [])
  const [recorded, setRecorded] = useState(false)
  const [reasoning, setReasoning] = useState('')
  const [videoPlaying, setVideoPlaying] = useState(false)
  const updateCell = (row: number, col: number, value: string) => setValues((current) => current.map((r, rIndex) => r.map((cell, cIndex) => (rIndex === row && cIndex === col ? Number(value) || 0 : cell))))
  return <div className="mx-auto max-w-6xl flex flex-col gap-8">
    <div><p className="text-sm text-primary">Learning Lab · Eigenvector Exploration</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Make your thinking visible.</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">Run an experiment, inspect the result, then capture the reasoning that turns an output into learning evidence.</p></div>
    <section className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]">
      <div className="rounded-2xl border border-border bg-card p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Matrix input</h2><p className="mt-1 text-sm text-muted-foreground">Edit the adjacency matrix for your network.</p></div><FlaskConical className="size-5 text-primary" /></div><div className="mt-6 grid max-w-sm grid-cols-5 gap-2">{values.map((row, rowIndex) => row.map((cell, colIndex) => <Input key={`${rowIndex}-${colIndex}`} value={cell} onChange={(event) => updateCell(rowIndex, colIndex, event.target.value)} className="h-12 text-center font-mono" aria-label={`Matrix row ${rowIndex + 1} column ${colIndex + 1}`} />))}</div><div className="mt-6 flex gap-3"><Button onClick={() => setRecorded(true)}><Play className="size-4" />Run experiment</Button><Button variant="outline" onClick={() => setValues(demoLabExperiments[0].matrixData?.values ?? [])}><RotateCcw className="size-4" />Reset</Button></div></div>
      <div className="rounded-2xl border border-border bg-card p-6"><p className="text-sm text-muted-foreground">Computed result</p><p className="mt-4 text-4xl font-semibold">λ₁ = 4.20</p><p className="mt-2 text-sm leading-relaxed text-muted-foreground">The dominant eigenvector highlights the most influential nodes in your network.</p><div className="mt-6 flex flex-col gap-3">{[0.58, 0.42, 0.31, 0.15, 0.18].map((value, index) => <div key={index} className="flex items-center gap-3 text-sm"><span className="w-12 text-muted-foreground">Node {index + 1}</span><div className="h-2 flex-1 rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{ width: `${value * 100}%` }} /></div><span className="font-mono text-xs">{value}</span></div>)}</div></div>
    </section>
    <section className="overflow-hidden rounded-2xl border border-primary/20 bg-primary/5"><div className="grid gap-6 p-6 md:grid-cols-[.9fr_1.1fr] md:p-8"><div><p className="text-sm font-medium uppercase tracking-[.16em] text-primary">Visual concept explanation</p><h2 className="mt-3 text-2xl font-semibold tracking-tight">See why the dominant eigenvector matters.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">A short visual walkthrough connects the matrix, the eigenvalue, and the nodes that carry the most influence.</p><Button className="mt-5" onClick={() => setVideoPlaying((current) => !current)}><Play className="size-4" /> {videoPlaying ? 'Pause explanation' : 'Watch explanation'}</Button></div><div className="relative min-h-52 overflow-hidden rounded-xl border border-border bg-background p-5"><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(to_right,rgba(255,255,255,.05)_1px,transparent_1px),linear-gradient(to_bottom,rgba(255,255,255,.05)_1px,transparent_1px)] [background-size:28px_28px]" /><div className="relative flex h-full min-h-44 items-center justify-center"><div className={`absolute left-[18%] top-[28%] size-4 rounded-full bg-primary shadow-[0_0_24px_rgba(100,220,160,.8)] ${videoPlaying ? 'animate-pulse' : ''}`} /><div className={`absolute left-[42%] top-[48%] size-6 rounded-full bg-primary shadow-[0_0_28px_rgba(100,220,160,.9)] ${videoPlaying ? 'animate-pulse' : ''}`} /><div className="absolute right-[20%] top-[25%] size-3 rounded-full bg-primary/70" /><div className="absolute bottom-[20%] right-[34%] size-4 rounded-full bg-primary/80" /><div className="absolute left-[21%] top-[34%] h-px w-[24%] rotate-[22deg] bg-primary/50" /><div className="absolute left-[47%] top-[46%] h-px w-[29%] -rotate-[24deg] bg-primary/50" /><div className="absolute left-[43%] top-[53%] h-px w-[20%] rotate-[34deg] bg-primary/40" /><div className="z-10 flex size-14 items-center justify-center rounded-full border border-primary/40 bg-primary/15 text-primary"><Volume2 className="size-5" /></div></div><div className="relative mt-2 flex items-center justify-between text-xs text-muted-foreground"><span>{videoPlaying ? 'Playing eigenvector walkthrough' : 'Eigenvector walkthrough'}</span><span>02:14</span></div></div></div></section>
    <section className="rounded-2xl border border-border bg-card p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Capture your reasoning</h2><p className="mt-1 text-sm text-muted-foreground">What does this result tell you, and what would you test next?</p></div>{recorded && <span className="flex items-center gap-1 text-sm text-primary"><Check className="size-4" /> Experiment recorded</span>}</div><textarea value={reasoning} onChange={(event) => setReasoning(event.target.value)} placeholder="I notice that..." className="mt-6 min-h-32 w-full resize-y rounded-xl border border-input bg-background px-4 py-3 text-sm text-foreground outline-none placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring" /><Button className="mt-4" onClick={() => setRecorded(true)}>Save as evidence</Button></section>
  </div>
}
